name: deploy-to-github-pages-name-in-yml-file
on:
  push:
    branches:
      - main
jobs:
  gh-pages-deploy:
    name: Deploying-to-gh-pages-name-of-job
    runs-on: ubuntu-latest
    concurrency: ci-${{github.ref}}
    steps:
      - name: Checkout-branch
        uses: actions/checkout@v3

      - name: Setup-Node-for-use-with-actions-step-name
        uses: actions/setup-node@v3
        with:
          node-version:  14.x

      - name: install-dependencies
        run: |
          npm install
          npm run build

      - name: Deploy-through-JamesIves
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          branch: gh-pages
          folder: dist
